[package]
name = "solana_assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dotenv = "0.15.0"
full = "0.3.0"
reqwest = "0.12.9"
rig-core = "0.6.0"
serde = "1.0.216"
serde_json = "1.0.134"
tokio = "1.42.0"
